### ISSUE TITLE
Set up call for talk proposals for 2019

### ISSUE THREAD

**Issue by blinry** [EnthusiastiCon/enthusiasticon.github.io#23]
We could probably reuse the call from last year? And remove all of the programme/speaker content? And plug in the new dates/locations?

**Comment by Dzol** [comment]
Yes, I think that's the idea, the others will correct me if I'm wrong 😺 We also have a revised form: https://goo.gl/forms/P7i8I0EG5QhKkDml1

**Comment by hellerve** [comment]
Yes, that sounds about right to me :+1:

**Comment by blinry** [comment]
I think this can be closed. :)
