### ISSUE TITLE
Invalid HTTPS

### ISSUE THREAD

**Issue by hellerve** [EnthusiastiCon/enthusiasticon.github.io#8]
HTTPS on https://enthusiasticon.de still uses Github’s SSL. This will show a warning to the user. I’d suggest we put [CloudFlare](https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc) or a similar service in front of it!

Cheers

**Comment by zormit** [comment]
Cool, didn't know cloudflare had a free tier. I'll see what I can do.

**Comment by zormit** [comment]
Theoretically I did set everything up as in the tutorial. Doesn't work though -- the DNS settings are pending to take effect, I guess.

**Comment by hellerve** [comment]
This could take a few hours. When did you set it up?

**Comment by zormit** [comment]
the NS was changed this morning, so it still has to be deployed on all DNS endpoints.

```
# G has it already:
$ dig @8.8.8.8 +short NS enthusiasticon.de
maria.ns.cloudflare.com.
noel.ns.cloudflare.com.

# the default for me not:
$ dig +short NS enthusiasticon.de         
ns6.kasserver.com.
ns5.kasserver.com.
```

**Comment by hellerve** [comment]
Cool!

**Comment by hellerve** [comment]
It works for me now, so I’ll close this issue as resolved. Thanks for your work!
